### ISSUE TITLE
can't find resource when install nova

### ISSUE THREAD

**Issue by suzhouclark** [crono782/openstack-ussuri-install#1]
when I go to install nova step, after input "dnf -y install openstack-nova-api openstack-nova-conductor openstack-nova-novncproxy openstack-nova-scheduler"
there are lot of error:

- nothing provides librte_vhost.so.4()(64bit) needed by openvswitch-2.12.0-1.el8.x86_64
  - nothing provides librte_vhost.so.4(DPDK_16.07)(64bit) needed by openvswitch-2.12.0-1.el8.x86_64
  - nothing provides librte_vhost.so.4(DPDK_17.05)(64bit) needed by openvswitch-2.12.0-1.el8.x86_64
  - nothing provides librte_vhost.so.4(DPDK_17.08)(64bit) needed by openvswitch-2.12.0-1.el8.x86_64
  - nothing provides librte_vhost.so.4(DPDK_2.0)(64bit) needed by openvswitch-2.12.0-1.el8.x86_64
  - nothing provides librte_vhost.so.4(DPDK_2.1)(64bit) needed by openvswitch-2.12.0-1.el8.x86_64

Could you please guide me how to resolve it ?

**Comment by crono782** [comment]
I am unable to duplicate the issue. I do see that openvswitch-2.12.0-1.1.el8.x86_64 is the package that is available from the ussuri repo. CentOS 8.2 was just released about the same time as your comment. Perhaps you just caught the repo in a transitory state while the mirrors were syncing. Worked fine for me on a test CentOS 8.2 VM.

**Comment by suzhouclark** [comment]
It works with 8.2.2004
